version: "3.9"

services:
  fastapi:
    build:
      context: .
    container_name: fastapi
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
